### ISSUE TITLE
Local/"user" installs

### ISSUE THREAD

**Issue by subsetpark** [janet-lang/jpm#17]
I'm curious what folks' opinions are about the intersection of `jpm --local` and `jpm install`.

---

Some package managers have a well-established concept of "local installs" - for instance, `pip --user` will install things in (I think??) `~/.local/bin`, so you can add that to your path and have local binaries that sit on a local tree.

By default, `jpm --local` uses `./jpm_tree` as its tree, including binaries. So I could add `~/jpm_tree/bin` to my path and get a roughly equivalent experience. 

However, there are two differences:

1. `~/jpm_tree` is not a "blessed" or "standard" directory in the way that `~/.local` is. It's also not hidden, which is a bit unusual - not a deal breaker, as I think Go tends to just chuck things in ~/go by default - but unusual.
2. `./jpm_tree` is a relative path, not an absolute one. So *if* I cd to `~` and then run `jpm --local install`, I'll get something in my "user" jpm bin directory. But if I'm elsewhere, it'll go elsewhere.

In general, though, I'm curious as to whether folks or @bakpakin have given any thought to this as a use case in general. As an application author, I'd like to make it as convenient as possible for users to install things to some equivalent of `~/bin` without having to 
- use `sudo`
- install global dependencies

I wonder if anyone feels similarly or has any thoughts about how to do that.

**Comment by subsetpark** [comment]
Thinking on this further:

one possible solution is to say that jpm is project-only, and to write a new script which is used for managing ‘local path’ binaries. This could be as simple as a wrapper around jpm combined with a config file that sets prefix to something like ‘~/.local/jpm’.

**Comment by bakpakin** [comment]
Local here means local to a project. Per user installs of package managers isn't really something I care about, you can install jpm to use user directories rather than system directories.

**Comment by bakpakin** [comment]
The config system is more than flexible enough to set this up, adding flags for global, user local, and project local is just silly since Janet itself doesn't even load packages that way.

**Comment by pyrmont** [comment]
@bakpakin When you say you can 'install jpm to use user directories', does this mean that in the JPM config file you would use `~` to set the `:modpath` key to somewhere within the respective user's home directory (e.g. `~/.jpm`)?

**Comment by bakpakin** [comment]
Yes, you can set up `jpm` to use a modpath in the a users home directory by default, but still load janet's headers and shared objects from a system directory.

**Comment by elimisteve** [comment]
> Yes, you can set up `jpm` to use a modpath in the a users home directory by default, but still load janet's headers and shared objects from a system directory.

Great! How?

**Comment by pyrmont** [comment]
@elimisteve I believe you either need to edit the global configuration file used by JPM such that `:modpath` uses `~` to point to somewhere in the current user's home directory or load a separate configuration file (using a command line switch) where you define `:modpath` to use a specific home directory.

**Comment by pyrmont** [comment]
@subsetpark This issue is a bit old at this point but I wanted to make a shameless plug that I nevertheless thought was relevant.

[Jeep](https://github.com/pyrmont/jeep) is an alternative Janet project manager I'm working on (still testing it out at the moment so it might break in unexpected ways). It sits in front of JPM and is meant to provide a few additional niceties. One of those is a new subcommand called **plonk** (as in '[plonk it down here](https://en.wiktionary.org/wiki/plonk)').

The plonk subcommand can be run with or without a repository argument. If run with a repository argument it will download that repository to a cache, build the executables (including dependencies) local to that cache and then copy the executables specified in that repository's project file to a binpath (by default, the system binpath).

So using Jeep you can install, say, [Bagatto](https://git.sr.ht/~subsetpark/bagatto)'s `bag` executable to your system binpath (e.g. `/usr/local/bin`) like this:

```shell
$ jeep plonk https://git.sr.ht/~subsetpark/bagatto
```

Alternatively, you could install `bag` to a given path like this:

```shell
$ jeep plonk https://git.sr.ht/~subsetpark/bagatto --binpath ~/bin
```

The plonk subcommand only copies the executable to the binpath. Everything else done is local to the cached directory and so (hopefully) won't otherwise affect your system.
